version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - celery-network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: poetry run celery -A chat_ai_worker.celery_config worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_BASE=${AZURE_OPENAI_API_BASE}
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - celery-network

networks:
  celery-network:
    driver: bridge
